### ISSUE TITLE
Recursion when starting

### ISSUE THREAD

**Issue by micheljung** [codefoster/waterbug-site#5]
Windows
```
npm install && npm start
```

```
> waterbug-server@0.1.0 start
> nodemon server.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js server.js server.js server.js server.js`
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `nodemon server.js server.js server.js server.js server.js server.js server.js server.js server.js`
Terminate batch job (Y/N)?
```

**Comment by micheljung** [comment]
Same on Linux

**Comment by micheljung** [comment]
Fixed `package.json` to point to `server.ts` instead of `server.js`. Installed node-ts:
```
npm install -D typescript
npm install -D ts-node
```
now I get:
```
/waterbug/waterbug-server/node_modules/ts-node/src/resolver-functions.ts:24
  const moduleResolutionCache = ts.createModuleResolutionCache(
                                   ^
TypeError: ts.createModuleResolutionCache is not a function
    at createResolverFunctions (/waterbug/waterbug-server/node_modules/ts-node/src/resolver-functions.ts:24:36)
    at create (/waterbug/waterbug-server/node_modules/ts-node/src/index.ts:867:34)
    at register (/waterbug/waterbug-server/node_modules/ts-node/src/index.ts:514:15)
    at main (/waterbug/waterbug-server/node_modules/ts-node/src/bin.ts:250:27)
    at Object.<anonymous> (/waterbug/waterbug-server/node_modules/ts-node/src/bin.ts:482:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

At this point, I lost interest.
